local M = {}

local icon = require("util.icon").icon(true)

M.config = {
  {
    "Bekaboo/dropbar.nvim",
    dependencies = {
      "nvim-telescope/telescope-fzf-native.nvim",
    },
    config = function()
      require("dropbar").setup({
        icons = {
          enable = true,
          kinds = {
            use_devicons = true,
            symbols = {
              Array = icon.Array,
              Boolean = icon.Boolean,
              BreakStatement = icon.BreakStatement,
              Call = icon.Call,
              CaseStatement = icon.CaseStatement,
              Class = icon.Class,
              Color = icon.Color,
              Constant = icon.Constant,
              Constructor = icon.Constructor,
              ContinueStatement = icon.ContinueStatement,
              Copilot = icon.Copilot,
              Declaration = icon.Declaration,
              Delete = icon.Delete,
              DoStatement = icon.DoStatement,
              Enum = icon.Enum,
              EnumMember = icon.EnumMember,
              Event = icon.Event,
              Field = icon.Field,
              File = icon.File,
              Folder = icon.Folder,
              ForStatement = icon.ForStatement,
              Function = icon.Function,
              H1Marker = icon.Header1,
              H2Marker = icon.Header2,
              H3Marker = icon.Header3,
              H4Marker = icon.Header4,
              H5Marker = icon.Header5,
              H6Marker = icon.Header6,
              Identifier = icon.Identifier,
              IfStatement = icon.IfStatement,
              Interface = icon.Interface,
              Keyword = icon.Keyword,
              List = icon.List,
              Log = icon.Log,
              Lsp = icon.Lsp,
              Macro = icon.Macro,
              MarkdownH1 = icon.Header1,
              MarkdownH2 = icon.Header2,
              MarkdownH3 = icon.Header3,
              MarkdownH4 = icon.Header4,
              MarkdownH5 = icon.Header5,
              MarkdownH6 = icon.Header6,
              Method = icon.Method,
              Module = icon.Module,
              Namespace = icon.Namespace,
              Null = icon.Null,
              Number = icon.Number,
              Object = icon.Object,
              Operator = icon.Operator,
              Package = icon.Package,
              Pair = icon.Pair,
              Property = icon.Property,
              Reference = icon.Reference,
              Regex = icon.Regex,
              Repeat = icon.Repeat,
              Scope = icon.Scope,
              Snippet = icon.Snippet,
              Specifier = icon.Specifier,
              Statement = icon.Statement,
              String = icon.String,
              Struct = icon.Struct,
              SwitchStatement = icon.SwitchStatement,
              Terminal = icon.Terminal,
              Text = icon.Text,
              Type = icon.Type,
              TypeParameter = icon.TypeParameter,
              Unit = icon.Unit,
              Value = icon.Value,
              Variable = icon.Variable,
              WhileStatement = icon.WhileStatement,
            },
          },
          ui = {
            bar = {
              separator = " ",
              extends = "…",
            },
            menu = {
              separator = " ",
              indicator = " ",
            },
          },
        },
      })
    end,
  },
}

return M
